### ISSUE TITLE
Azure deployment broken again

### ISSUE THREAD

**Issue by shaunakv1** [mko-x/docker-clamav#92]
**Describe the bug**
It seems the issue that was fixed a couple of months back (https://github.com/mko-x/docker-clamav/issues/78) is now happening again breaking azure container deployment. Here are the tickets I believe changes for which broke this again: https://github.com/mko-x/docker-clamav/issues/89

**To Reproduce**
This is deployed to azure in a fairly standard way using container instances. Here's the azure yaml file that does the deploy: 

![image](https://user-images.githubusercontent.com/732604/101269138-13338200-3731-11eb-893f-ce9e443adaa7.png)

**Expected behavior**
Usually the image updates the database and boots up, but at some point within last few days, after a new image pull the image won't start anymore. No configuration has changed otherwise. 

**Screenshots**
![image](https://user-images.githubusercontent.com/732604/97016425-5388c900-1512-11eb-8f67-208ba7127815.png)

**Host (please complete the following information):**
 - OS: Azure
 -  Container Instances

**Image (please complete the following information):**
 - Tag: mkodockx/docker-clamav:latest   but all tags have the same issue. Alpine, latest, alpine edge etc. 
 - Configuration: N/A

**Additional context**
 Interesting thing is the image boots up just fine if we pull it down to local docker host on a VM.  Throws the above error only when deployed to azure container instances

**Comment by mko-x** [comment]
@WhiteBahamut : is it possible? maybe another line ending issue

**Comment by shaunakv1** [comment]
Here's the latest deploy specs and full log: 
![image](https://user-images.githubusercontent.com/732604/101269133-07e05680-3731-11eb-8dd7-5d28f6a429b6.png)



```bash
λ az container logs --follow --resource-group ocm-webops-eastus2-rg --name ocm-web-clamav
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tm[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
[bootstrap] Initial clam DB download.
Sun Dec  6 01:28:57 2020 -> ClamAV update process started at Sun Dec  6 01:28:57 2020
Sun Dec  6 01:28:57 2020 -> daily database available for download (remote version: 26009)
Sun Dec  6 01:29:04 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-6da82353158557c70956a69fe4e1f522.tmp-daily.cvd' ...
Sun Dec  6 01:29:51 2020 -> Database test passed.
Sun Dec  6 01:29:51 2020 -> daily.cvd updated (version: 26009, sigs: 4351133, f-level: 63, builder: raynman)
Sun Dec  6 01:29:51 2020 -> main database available for download (remote version: 59)
Sun Dec  6 01:29:57 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-a756aa92249de6e6fc879a3a4350fa3e.tmp-main.cvd' ...
Sun Dec  6 01:30:09 2020 -> Database test passed.
Sun Dec  6 01:30:09 2020 -> main.cvd updated (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Sun Dec  6 01:30:09 2020 -> bytecode database available for download (remote version: 331)
Sun Dec  6 01:30:09 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-5f642c36c1e54dc4527a6e9519608a22.tmp-bytecode.cvd' ...
Sun Dec  6 01:30:09 2020 -> Database test passed.
Sun Dec  6 01:30:09 2020 -> bytecode.cvd updated (version: 331, sigs: 94, f-level: 63, builder: anvilleg)
Sun Dec  6 01:30:09 2020 -> safebrowsing database available for download (remote version: 49191)
Sun Dec  6 01:30:11 2020 -> Testing database: '/var/lib/clamav/tmp.6c5ca/clamav-636995ec11b8f19c42f3dbe8fec31073.tmp-safebrowsing.cvd' ...
Sun Dec  6 01:30:17 2020 -> Database test passed.
Sun Dec  6 01:30:17 2020 -> safebrowsing.cvd updated (version: 49191, sigs: 2213119, f-level: 63, builder: google)
Sun Dec  6 01:30:17 2020 -> ^Clamd was NOT notified: Can't connect to clamd through /run/clamav/clamd.sock: No such file or directory
[bootstrap] Schedule freshclam DB updater.
[bootstrap] Run clamav daemon...
Sun Dec  6 01:31:28 2020 -> !LOCAL: Could not create socket directory: /run/clamav: Permission denied
Sun Dec  6 01:31:28 2020 -> !LOCAL: Ensure parent directory exists.
Sun Dec  6 01:31:28 2020 -> !LOCAL: Socket file /run/clamav/clamd.sock could not be bound: No such file or directory
Sun Dec  6 01:31:28 2020 -> !Can't unlink the socket file /run/clamav/clamd.sock
```

**Comment by WhiteBahamut** [comment]
Do you see the image hash somewhere? And while the container is running (during db updates) can you exec into it and check `ls -l /run/` and `top`. Want to check if  `/run/clamav` exists and what permissions are set so I can compare it to user clam is running. Oh and maybe a `id` as well.

Just wondering why Azure complains about things all the time -.-'

**Comment by DavidJFowler** [comment]
Hi. I'm seeing the same issue but it only appears to happen in one Azure subscription. I can deploy the same image, from the same repository, to a container instance in another subscription and clam av starts fine.

This is my Dockerfile, I'm just updating some max size settings:
```
FROM mkodockx/docker-clamav:alpine

COPY ./config/clamd.conf /etc/clamav/clamd.conf
COPY ./config/freshclam.conf /etc/clamav/freshclam.conf
```

**Comment by mko-x** [comment]
Seems like the error is in Azure container system.

**Comment by Mik4sa** [comment]
I also had problems with specific versions of this image. Though, it should be fixed now. You may try to reboot your containers so that they pull new images and check your case again.

**Comment by mko-x** [comment]
Could someone please check that issue with the latest release in Azure?

**Comment by DavidJFowler** [comment]
Still getting error
```
Wed Dec 16 09:02:37 2020 -> ^Clamd was NOT notified: Can't connect to clamd through /run/clamav/clamd.sock: No such file or directory
[bootstrap] Schedule freshclam DB updater.
[bootstrap] Run clamav daemon...
Wed Dec 16 09:04:12 2020 -> !LOCAL: Could not create socket directory: /run/clamav: Permission denied
Wed Dec 16 09:04:12 2020 -> !LOCAL: Ensure parent directory exists.
Wed Dec 16 09:04:12 2020 -> !LOCAL: Socket file /run/clamav/clamd.sock could not be bound: No such file or directory
Wed Dec 16 09:04:12 2020 -> !Can't unlink the socket file /run/clamav/clamd.sock
```

Deployed with Azure CLI into new container instance:

```
az container create --resource-group xxxx-rg --name xxxx --image mkodockx/docker-clamav:alpine --cpu 1 --memory 2  --dns-name-label xxxx --ports 3310
```

**Comment by WhiteBahamut** [comment]
Does this ensure a force pull of the image?

**Comment by DavidJFowler** [comment]
It now appears to be working for me.
